### ISSUE TITLE
bug with numbers 

### ISSUE THREAD

**Issue by michaelthomason87** [michaelthomason87/guessingGame.java#7]
the 81 conundrum???

**Comment by DeathCamel57** [comment]
The issue was related to including the number that it's asking if yours is above or below.

When choosing number 81..
Variables:
- `minThreshold = 80`
- `maxThreshold = 81`

When it asks...

- `Is your number greater than or equal to 80? (press y/n)`
It makes the `minThreshold` variable 80, as the question includes the number 80.

- `Is your number less than or equal to 80? (press y/n)`
When you select choose `n`, it just sets `minThreshold` to 80, not one higher, causing the two variables not to change. 

There has been a **quick fix** that works applied.
**However**, I am going to attempt an edit that would require less code being edited in `master`.

**Comment by DeathCamel57** [comment]
I tried the smaller fix. 
**However**, it didn't work properly, and there was the same issue. I will merge commit **`5d7a88d`**, into master now.

#closed
